---
apiVersion: v2
description: Chart for Homepage
icon: https://github.com/gethomepage/homepage/blob/main/public/mstile-150x150.png
name: homepage
version: 2.0.2
appVersion: v0.9.9
sources:
  - https://github.com/jameswynn/helm-charts/charts/homepage
  - https://github.com/gethomepage/homepage/
maintainers:
  - name: jameswynn
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.3.1
annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: Checksum of values added to the deployment to ensure config changes cause reload
